### ISSUE TITLE
Selection don't work on Python 3.7

### ISSUE THREAD

**Issue by josepmy** [RedFT/HexyExamples#2]
Hi,

The selection scroll don't work on python 3.7. For example scroll up and down to change the radius of selection when selection type is ring or disk.
Where I can help to build a python 3.7 compatible version?

**Comment by josepmy** [comment]
This is what don't work.

scroll up and down to change the radius of selection when selection type is ring or disk.

**Comment by josepmy** [comment]
In python 3.7 map return an object, so must use list()

list(map(lambda hexagon:
                self.main_surf.blit(self.selected_hex_image, hexagon.get_draw_position() + self.center),hexes
            ))

**Comment by RedFT** [comment]
Hi Joseph,

If you'd like to fix this, here are the steps:

1. Fork this repo on GitHub.
2. Clone the fork to your computer.
3. Make the change on your computer.
4. Then commit your changes on your computer.
5. Push your changes to your fork 
6. Make a pull request on this repo.

**Comment by josepmy** [comment]
OK. Yes, I finally fixed it.
Today send the PR

**Comment by RedFT** [comment]
Any updates?

**Comment by josepmy** [comment]
WIP

**Comment by josepmy** [comment]
PR pending

**Comment by RedFT** [comment]
PR merged

**Comment by RedFT** [comment]
https://github.com/RedFT/HexyExamples/pull/3
